export const resources = [
  {
    name: "Pixelcut AI - Upscaler",
    description: "Upscaler de imagenes gracias a IA",
    url: "https://www.pixelcut.ai/t/upscaler",
    icon: "https://www.pixelcut.ai/favicon.ico",
    categories: ["Imágen", "IA"],
  },
  {
    name: "Codi Link",
    description: "Editor de código online de HTML, JS, y CSS",
    url: "https://codi.link",
    icon: "https://code.visualstudio.com/assets/apple-touch-icon.png",
    categories: ["Programación"],
  },
  {
    name: "Simulador móvil",
    description: "Simulador de smartphones y tablets muy realista.",
    url: "https://chromewebstore.google.com/detail/simulador-m%C3%B3vil-herramien/ckejmhbmlajgoklhgbapkiccekfoccmk?hl=es",
    icon: "https://lh3.googleusercontent.com/AdZGgDWDCE3zyp1t_rJo1VT_9ge6l7QeFftWKrr2opJc4IgOmbQY82_4s44rGpHqZjw6ALtEsjlY8Sv1nERN-nAJEA=s120",
    categories: ["Chrome"],
  },
  {
    name: "es6-string-html",
    description: "Interpreta HTML en query strings de javascript.",
    url: "https://marketplace.visualstudio.com/items?itemName=Tobermory.es6-string-html",
    icon: "https://tobermory.gallerycdn.vsassets.io/extensions/tobermory/es6-string-html/2.17.0/1733307395603/Microsoft.VisualStudio.Services.Icons.Default",
    categories: ["VS Code"],
  },
  {
    name: "Photopea",
    description: "Clon de Photoshop gratuito online.",
    url: "https://www.photopea.com/",
    icon: "https://www.photopea.com/promo/icon512.png",
    categories: ["Imágen"],
  },
  // AI
  {
    name: "JSON Crack",
    description: "Visualizador de JSON interactivo y elegante",
    url: "https://jsoncrack.com/",
    icon: "https://jsoncrack.com/assets/192.png",
    categories: ["Programación", "Herramientas"],
  },
  {
    name: "Regex101",
    description: "Editor y tester de expresiones regulares en tiempo real",
    url: "https://regex101.com/",
    icon: "https://regex101.com/static/assets/favicon.ico",
    categories: ["Programación", "Herramientas"],
  },
  {
    name: "Carbon",
    description: "Crea hermosas imágenes de tu código fuente",
    url: "https://carbon.now.sh/",
    icon: "https://carbon.now.sh/favicon.ico",
    categories: ["Programación", "Imágen"],
  },
  {
    name: "Excalidraw",
    description: "Pizarra virtual para diagramas y bocetos",
    url: "https://excalidraw.com/",
    icon: "https://excalidraw.com/favicon.ico",
    categories: ["Diseño", "Herramientas"],
  },
  {
    name: "TinyPNG",
    description: "Compresor de imágenes PNG y JPEG sin pérdida de calidad",
    url: "https://tinypng.com/",
    icon: "https://tinypng.com/images/favicon.ico",
    categories: ["Imágen", "Optimización"],
  },
  {
    name: "Htmlrev",
    description: "Plantillas html",
    url: "https://htmlrev.com/",
    icon: "https://htmlrev.com/images/logo.svg",
    categories: ["Programación", "Herramientas"],
  },
];
